---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-path-type
  labels:
    domain: bugbash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: echo-path-type
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 3
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: gcr.io/google_containers/echoserver:1.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: echo-path-type
  name: echo
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: echo
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: echo-path-type
  name: echo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /prefix
            pathType: Prefix
            backend:
              serviceName: echo
              servicePort: 80
          - path: /imp-specific
            backend:
              serviceName: echo
              servicePort: 80
          - path: /
            pathType: Exact
            backend:
              serviceName: echo
              servicePort: 80